In [1]:
import numpy as np
import pandas as pd

## 인구데이터 통합

In [2]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '상주인구_전처리.csv'
pop_sj = pd.read_csv(filepath+filename, encoding='cp949')

filename = '직장인구_전처리.csv'
pop_jj = pd.read_csv(filepath+filename, encoding='cp949')

filename = '생활인구_1주샘플_전처리.csv'
pop_sh = pd.read_csv(filepath+filename, encoding='cp949')

filename = '인구밀도_전처리.csv'
pop_density = pd.read_csv(filepath+filename, encoding='cp949')

In [3]:
pop_sj

    행정구역  20대이상 상주인구수
0    강남구       453493
1    강동구       346157
2    강북구       283097
3    강서구       507030
4    관악구       441834
5    광진구       302533
6    구로구       349639
7    금천구       196670
8    노원구       482787
9    도봉구       301416
10  동대문구       285679
11   동작구       334688
12   마포구       313910
13  서대문구       263104
14   서초구       338986
15   성동구       250086
16   성북구       358182
17   송파구       542970
18   양천구       398269
19  영등포구       305143
20   용산구       194095
21   은평구       400927
22   종로구       128826
23    중구       108970
24   중랑구       348915

In [4]:
pop_sh

    행정구역  20대이상_생활인구수_1주합계  20대이상_생활인구수_하루평균
0    강남구         128039043          18291291
1    강동구          76164997          10880713
2    강북구          42595191           6085027
3    강서구          82893393          11841913
4    관악구          73000752          10428678
5    광진구          56719802           8102828
6    구로구          60582932           8654704
7    금천구          34949619           4992802
8    노원구          72837892          10405413
9    도봉구          39867763           5695394
10  동대문구          55317631           7902518
11   동작구          58637990           8376855
12   마포구          71418047          10202578
13  서대문구          57489679           8212811
14   서초구          88314071          12616295
15   성동구          54421232           7774461
16   성북구          64522806           9217543
17   송파구         112559512          16079930
18   양천구          54442204           7777457
19  영등포구          75951926          10850275
20   용산구          44461012           6351573
21   은평구          64420833           9202976
22   종로구          45581014           6511573
23    중구          44076848           6296692
24   중랑구          52629889           7518555

In [5]:
pop = pd.merge(pop_sj, pop_sh, on='행정구역')
pop = pd.merge(pop, pop_jj, on='행정구역')
pop = pd.merge(pop, pop_density, on='행정구역')

In [6]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   행정구역              25 non-null     object
 1   20대이상 상주인구수       25 non-null     int64
 2   20대이상_생활인구수_1주합계  25 non-null     int64
 3   20대이상_생활인구수_하루평균  25 non-null     int64
 4   20대이상 직장인구수       25 non-null     int64
 5   인구 (명)            25 non-null     int64
 6   면적 (㎢)            25 non-null     float64
 7   인구밀도 (명/㎢)        25 non-null     int64
dtypes: float64(1), int64(6), object(1)
memory usage: 1.7+ KB

In [7]:
#인구 데이터 정리
pop

,행정구역,20대이상 상주인구수,20대이상_생활인구수_1주합계,20대이상_생활인구수_하루평균,20대이상 직장인구수,인구 (명),면적 (㎢),인구밀도 (명/㎢)
0,강남구,453493,128039043,18291291,1117095,550282,39.50,13932
1,강동구,346157,76164997,10880713,74847,463318,24.59,18841
2,강북구,283097,42595191,6085027,28186,292977,23.60,12414
3,강서구,507030,82893393,11841913,149430,568826,41.45,13723
4,관악구,441834,73000752,10428678,72664,497883,29.57,16838
5,광진구,302533,56719802,8102828,81014,351180,17.06,20582
6,구로구,349639,60582932,8654704,139373,415651,20.12,20656
7,금천구,196670,34949619,4992802,126000,241105,13.02,18517
8,노원구,482787,72837892,10405413,56542,502925,35.44,14191
9,도봉구,301416,39867763,5695394,36328,309494,20.65,14987
10,동대문구,285679,55317631,7902518,80132,359873,14.22,25315
11,동작구,334688,58637990,8376855,77881,389714,16.36,23826
12,마포구,313910,71418047,10202578,142218,375162,23.85,15727
13,서대문구,263104,57489679,8212811,65977,320629,17.63,18190
14,서초구,338986,88314071,12616295,575078,412078,46.97,8774
15,성동구,250086,54421232,7774461,80349,284766,16.82,16930
16,성북구,358182,64522806,9217543,110066,438168,24.58,17828
17,송파구,542970,112559512,16079930,398845,660025,33.88,19483
18,양천구,398269,54442204,7777457,139145,439252,17.41,25236
19,영등포구,305143,75951926,10850275,396721,397800,24.55,16203
20,용산구,194095,44461012,6351573,175671,227106,21.87,10386
21,은평구,400927,64420833,9202976,48814,470869,29.71,15849
22,종로구,128826,45581014,6511573,232005,150453,23.91,6292
23,중구,108970,44076848,6296692,332874,131793,9.96,13232
24,중랑구,348915,52629889,7518555,39237,387470,18.50,20948

## 주차 관련 데이터

In [8]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '서울공영주차장수_전처리.csv'
parkinglot = pd.read_csv(filepath+filename, encoding='cp949')

In [9]:
parkinglot

      구명  주차장수    총주차면     주차장당주차면
0    강남구   112  6394.0   57.089286
1    강동구    31  3512.0  113.290323
2    강북구    46  2585.0   56.195652
3    강서구    93  6436.0   69.204301
4    관악구    32  1708.0   53.375000
5    광진구    45  1743.0   38.733333
6    구로구    42  2686.0   63.952381
7    금천구   250  3312.0   13.248000
8    노원구    53  2322.0   43.811321
9    도봉구    30  2140.0   71.333333
10  동대문구    68  3938.0   57.911765
11   동작구    74  1482.0   20.027027
12   마포구    93  3941.0   42.376344
13  서대문구    19   663.0   34.894737
14   서초구    58  5546.0   95.620690
15   성동구   238  6759.0   28.399160
16   성북구    21   928.0   44.190476
17   송파구   265  7751.0   29.249057
18   양천구   101  6388.0   63.247525
19  영등포구   157  5908.0   37.630573
20   용산구    57  4009.0   70.333333
21   은평구    13  1571.0  120.846154
22   종로구    88  4480.0   50.909091
23    중구   166  6230.0   37.530120
24   중랑구    73  2884.0   39.506849

## 주차혼잡데이터 통합

In [10]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '교통혼잡비용,시간,빈도,속도_전처리.csv'
traffic = pd.read_csv(filepath+filename, encoding='cp949')

filename = '서울 구별 평균도로혼잡빈도강도_전처리.csv'
traffic_2 = pd.read_csv(filepath+filename, encoding='cp949')

filename = '서울(구별) 택시통행량_전처리.csv'
taxi = pd.read_csv(filepath+filename, encoding='cp949')

In [11]:
traffic = traffic.drop('Unnamed: 0', axis=1)

In [12]:
traffic_2 = traffic_2.drop('Unnamed: 0', axis=1)

In [13]:
taxi = taxi.drop('Unnamed: 0', axis=1)

In [14]:
traffic.columns

Index(['시군구명', 'COST_CG_sum(억)', 'COST_CG_mean(억)', 'FRIN_CG_sum',
       'FRIN_CG_mean', 'TI_CG_sum', 'TI_CG_mean', 'velocity_CG_AVRG'],
      dtype='object')

In [15]:
traffic_2.columns

Index(['signgu_nm', 'ave_road_cfi'], dtype='object')

In [16]:
taxi.columns

Index(['시군구명', 'ave_txtr'], dtype='object')

In [17]:
traffic_final = pd.merge(traffic, traffic_2, left_on='시군구명', right_on='signgu_nm').drop('signgu_nm', axis=1)
traffic_final = pd.merge(traffic_final, taxi, on='시군구명')

In [18]:
#교통혼잡데이터 최종
traffic_final

,시군구명,COST_CG_sum(억),COST_CG_mean(억),FRIN_CG_sum,FRIN_CG_mean,TI_CG_sum,TI_CG_mean,velocity_CG_AVRG,ave_road_cfi,ave_txtr
0,강남구,14694.59,667.94,1233.56,56.070909,1603.18,72.871818,16.868182,44.576364,688.645455
1,강동구,4401.15,244.51,1118.55,62.141667,1344.09,74.671667,18.257222,55.933333,411.566667
2,강북구,1971.17,151.63,663.44,51.033846,877.37,67.490000,16.335385,57.950000,433.650000
3,강서구,7215.73,360.79,1101.02,55.051000,1374.46,68.723000,17.758500,63.733333,368.933333
4,관악구,3699.58,176.17,844.84,40.230476,1222.13,58.196667,15.744286,48.600000,642.322222
5,광진구,4577.80,305.19,1099.74,73.316000,1260.14,84.009333,20.060000,68.466667,598.966667
6,구로구,5283.82,330.24,866.82,54.176250,1109.13,69.320625,16.626875,54.330000,406.280000
7,금천구,4429.13,442.91,553.62,55.362000,682.07,68.207000,17.891000,54.016667,397.200000
8,노원구,4313.31,227.02,1154.77,60.777368,1403.19,73.852105,19.152632,68.650000,297.175000
9,도봉구,2055.09,146.79,747.68,53.405714,964.21,68.872143,16.390714,49.300000,233.200000
10,동대문구,3866.23,276.16,769.89,54.992143,996.51,71.179286,16.910714,49.622222,334.133333
11,동작구,3394.38,226.29,723.70,51.692857,944.78,67.484286,16.158667,36.657143,431.257143
12,마포구,7458.26,466.14,1164.83,72.801875,1333.33,83.333125,19.761250,63.610000,554.310000
13,서대문구,3874.44,276.75,919.86,65.704286,1107.24,79.088571,17.540714,76.766667,437.200000
14,서초구,12702.69,705.70,986.25,54.791667,1268.11,70.450556,17.462222,48.575000,617.504167
15,성동구,4336.05,255.06,890.07,52.357059,1182.79,69.575882,18.318824,33.975000,330.000000
16,성북구,4223.69,211.18,1175.51,58.775500,1475.23,73.761500,17.246000,48.966667,355.350000
17,송파구,8572.07,317.48,1407.72,52.137778,1829.55,67.761111,17.677407,52.788889,506.088889
18,양천구,4517.14,250.95,760.66,42.258889,1094.85,60.825000,16.058889,43.480000,455.320000
19,영등포구,9122.09,506.78,878.09,48.782778,1191.29,66.182778,16.715000,47.676923,408.923077
20,용산구,4884.96,305.31,821.91,51.369375,1057.59,66.099375,17.530000,41.120000,517.700000
21,은평구,3654.13,228.38,1017.09,63.568125,1237.18,77.323750,16.128750,66.200000,488.425000
22,종로구,4422.40,276.40,965.31,60.331875,1177.25,73.578125,16.551250,69.303846,404.969231
23,중구,3867.61,257.84,719.07,47.938000,1011.90,67.460000,14.592667,48.052632,422.505263
24,중랑구,3907.33,244.21,1039.61,64.975625,1224.05,76.503125,18.633125,52.300000,416.700000

## 주차 수요 및 공급 관련 데이터 통합

In [19]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '서울시 구별 주차가능점포수_전처리.csv'
res_parking = pd.read_csv(filepath+filename, encoding='cp949')

filename = '장애인주차구역과태료_전처리.csv'
fine = pd.read_csv(filepath+filename, encoding='cp949')

filename = '서울_점포수.csv'
place = pd.read_csv(filepath+filename, encoding='cp949')

In [20]:
res_parking = res_parking.drop('Unnamed: 0', axis=1)

In [21]:
fine = fine.drop('Unnamed: 0', axis=1)

In [22]:
fine.columns

Index(['시군구명', 'fine_count', 'fine_sum(천)'], dtype='object')

In [23]:
place = place.drop('Unnamed: 0', axis=1)

In [24]:
place = pd.merge(res_parking, place, left_on='지역명', right_on='행정구역').drop('행정구역', axis=1).rename({'주차가능점포수':'주차가능식당수','전체점포수':'전체식당수', '주차가능점포비율':'주차가능식당(%)','점포수 2023':'전체점포수' }, axis=1)

In [25]:
supply = pd.merge(fine, place,  left_index=True, right_index=True).drop('지역명', axis=1)

In [26]:
#장애인구역 과태료 부과 데이터, 점포수 관련 데이터
supply

      시군구명  fine_count  fine_sum(천)  주차가능식당수  전체식당수  주차가능식당(%)  전체점포수
0     강남구         6135    546904.20     2253  14504  15.533646  60485
1     강동구         2307    184200.00      658   4712  13.964346  22598
2     강북구         1745    148504.00      333   3756   8.865815  14168
3     강서구         5443    447509.00     1184   6890  17.184325  30196
4     관악구         1776    152020.00      511   5238   9.755632  20843
5     광진구         1594    133660.00      558   4958  11.254538  19817
6     구로구         2355    209330.00      505   4519  11.175039  23539
7     금천구         2208    208510.00      456   3393  13.439434  17631
8     노원구         2521    201200.00      562   4341  12.946326  19936
9     도봉구         1948    169470.00      280   2629  10.650437  12345
10   동대문구         5432    448580.00      416   4741   8.774520  21480
11    동작구         1982    161890.00      371   3610  10.277008  16524
12    마포구         3096    269650.00     1093   8998  12.147144  31597
13   서대문구         1245    124500.00      364   4363   8.342883  15744
14    서초구         3257    269840.00     1320   6984  18.900344  37965
15    성동구         2264    195190.00      442   4226  10.459063  19892
16    성북구         1336    114600.00      477   4675  10.203209  18752
17    송파구         4656    409090.00     1443   8398  17.182663  40619
18    양천구         1977    171680.00      489   3648  13.404605  19452
19   영등포구         4902    451500.00     1077   8003  13.457453  29239
20    용산구         1438    138260.00      516   5382   9.587514  19487
21    은평구         1220    108620.00      516   4507  11.448857  19786
22    종로구          892     75000.26      606   8078   7.501857  25838
23     중구         2154    185440.00      584   7741   7.544245  37883
24    중랑구         1573    132493.00      389   4126   9.428017  17439

### 교통량 데이터 추가

In [27]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '대중교통_목적도착지_승객수_전처리.csv'
trans = pd.read_csv(filepath+filename, encoding='cp949')

In [28]:
trans.columns

Index(['구별구분', '목적도착지_승객수_1주합계', '목적도착지_승객수_하루평균'], dtype='object')

In [29]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '서울교통량데이터_전처리.csv'
traffic4 = pd.read_csv(filepath+filename, encoding='cp949')

In [30]:
traffic4.columns

Index(['구별구분', '교통량_합계'], dtype='object')

### 불법주정차 단속 데이터 추가

In [31]:
filepath = 'C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/'

filename = '불법주정차데이터_전처리.csv'
law = pd.read_csv(filepath+filename, encoding='cp949')

In [32]:
law.columns

Index(['구별구분', '불법주차수'], dtype='object')

## merge 활용 순차적으로 데이터 붙이기
- 합칠 데이터 목록
  - parking_all 
  - pop 
  - traffic_final 
  - supply
  - trans
  - traffic4
  - law

In [33]:
#순차적으로 데이터 붙이기
data_set = pd.merge(parkinglot, pop, left_on='구명', right_on='행정구역').drop('행정구역', axis=1)
data_set = pd.merge(data_set, traffic_final, left_on='구명', right_on='시군구명').drop('시군구명', axis=1)
data_set = pd.merge(data_set, supply, left_index=True, right_index=True).drop('시군구명', axis=1)
data_set = pd.merge(data_set, trans, left_index=True, right_index=True).drop('구별구분', axis=1)
data_set = pd.merge(data_set, traffic4, left_index=True, right_index=True).drop('구별구분', axis=1)
data_set = pd.merge(data_set, law, left_index=True, right_index=True).drop('구별구분', axis=1)

In [34]:
data_set

,구명,주차장수,총주차면,주차장당주차면,20대이상 상주인구수,20대이상_생활인구수_1주합계,20대이상_생활인구수_하루평균,20대이상 직장인구수,인구 (명),면적 (㎢),...,fine_count,fine_sum(천),주차가능식당수,전체식당수,주차가능식당(%),전체점포수,목적도착지_승객수_1주합계,목적도착지_승객수_하루평균,교통량_합계,불법주차수
0,강남구,112,6394.0,57.089286,453493,128039043,18291291,1117095,550282,39.50,...,6135,546904.20,2253,14504,15.533646,60485,4809502,687071,21788199.0,72916
1,강동구,31,3512.0,113.290323,346157,76164997,10880713,74847,463318,24.59,...,2307,184200.00,658,4712,13.964346,22598,1386505,198072,8209451.0,100629
2,강북구,46,2585.0,56.195652,283097,42595191,6085027,28186,292977,23.60,...,1745,148504.00,333,3756,8.865815,14168,1260987,180141,0.0,37732
3,강서구,93,6436.0,69.204301,507030,82893393,11841913,149430,568826,41.45,...,5443,447509.00,1184,6890,17.184325,30196,2237554,319650,8939008.0,18184
4,관악구,32,1708.0,53.375000,441834,73000752,10428678,72664,497883,29.57,...,1776,152020.00,511,5238,9.755632,20843,2725974,389424,2365692.0,93184
5,광진구,45,1743.0,38.733333,302533,56719802,8102828,81014,351180,17.06,...,1594,133660.00,558,4958,11.254538,19817,1842373,263196,3999728.0,96249
6,구로구,42,2686.0,63.952381,349639,60582932,8654704,139373,415651,20.12,...,2355,209330.00,505,4519,11.175039,23539,1788097,255442,4479554.0,42590
7,금천구,250,3312.0,13.248000,196670,34949619,4992802,126000,241105,13.02,...,2208,208510.00,456,3393,13.439434,17631,1059898,151414,8807172.0,49686
8,노원구,53,2322.0,43.811321,482787,72837892,10405413,56542,502925,35.44,...,2521,201200.00,562,4341,12.946326,19936,1854488,264926,11007714.0,49783
9,도봉구,30,2140.0,71.333333,301416,39867763,5695394,36328,309494,20.65,...,1948,169470.00,280,2629,10.650437,12345,1056529,150932,2093756.0,30739
10,동대문구,68,3938.0,57.911765,285679,55317631,7902518,80132,359873,14.22,...,5432,448580.00,416,4741,8.774520,21480,1633119,233302,3748974.0,93035
11,동작구,74,1482.0,20.027027,334688,58637990,8376855,77881,389714,16.36,...,1982,161890.00,371,3610,10.277008,16524,1795550,256507,7818022.0,8085
12,마포구,93,3941.0,42.376344,313910,71418047,10202578,142218,375162,23.85,...,3096,269650.00,1093,8998,12.147144,31597,3003919,429131,17796569.0,221990
13,서대문구,19,663.0,34.894737,263104,57489679,8212811,65977,320629,17.63,...,1245,124500.00,364,4363,8.342883,15744,1687487,241069,6416421.0,62506
14,서초구,58,5546.0,95.620690,338986,88314071,12616295,575078,412078,46.97,...,3257,269840.00,1320,6984,18.900344,37965,3548234,506890,23313998.0,194081
15,성동구,238,6759.0,28.399160,250086,54421232,7774461,80349,284766,16.82,...,2264,195190.00,442,4226,10.459063,19892,1871714,267387,8533247.0,49465
16,성북구,21,928.0,44.190476,358182,64522806,9217543,110066,438168,24.58,...,1336,114600.00,477,4675,10.203209,18752,1912175,273167,7232546.0,62491
17,송파구,265,7751.0,29.249057,542970,112559512,16079930,398845,660025,33.88,...,4656,409090.00,1443,8398,17.182663,40619,3172030,453147,13757477.0,141810
18,양천구,101,6388.0,63.247525,398269,54442204,7777457,139145,439252,17.41,...,1977,171680.00,489,3648,13.404605,19452,1354240,193462,7319098.0,109941
19,영등포구,157,5908.0,37.630573,305143,75951926,10850275,396721,397800,24.55,...,4902,451500.00,1077,8003,13.457453,29239,2908672,415524,16027166.0,123521
20,용산구,57,4009.0,70.333333,194095,44461012,6351573,175671,227106,21.87,...,1438,138260.00,516,5382,9.587514,19487,1565788,223684,15715700.0,163903
21,은평구,13,1571.0,120.846154,400927,64420833,9202976,48814,470869,29.71,...,1220,108620.00,516,4507,11.448857,19786,1739307,248472,3711887.0,64089
22,종로구,88,4480.0,50.909091,128826,45581014,6511573,232005,150453,23.91,...,892,75000.26,606,8078,7.501857,25838,2998643,428377,5971573.0,76791
23,중구,166,6230.0,37.530120,108970,44076848,6296692,332874,131793,9.96,...,2154,185440.00,584,7741,7.544245,37883,3730842,532977,11034934.0,115530
24,중랑구,73,2884.0,39.506849,348915,52629889,7518555,39237,387470,18.50,...,1573,132493.00,389,4126,9.428017,17439,1249240,178462,4931913.0,43823

In [35]:
data_set.columns

Index(['구명', '주차장수', '총주차면', '주차장당주차면', '20대이상 상주인구수', '20대이상_생활인구수_1주합계',
       '20대이상_생활인구수_하루평균', '20대이상 직장인구수', '인구 (명)', '면적 (㎢)', '인구밀도 (명/㎢)',
       'COST_CG_sum(억)', 'COST_CG_mean(억)', 'FRIN_CG_sum', 'FRIN_CG_mean',
       'TI_CG_sum', 'TI_CG_mean', 'velocity_CG_AVRG', 'ave_road_cfi',
       'ave_txtr', 'fine_count', 'fine_sum(천)', '주차가능식당수', '전체식당수',
       '주차가능식당(%)', '전체점포수', '목적도착지_승객수_1주합계', '목적도착지_승객수_하루평균', '교통량_합계',
       '불법주차수'],
      dtype='object')

In [36]:
data_set.to_csv('C:/Users/jelly/Desktop/패스트캠퍼스 부트캠프/4. 프로젝트/python_3조/주차장/전처리 완료/주차장 데이터 전처리_통합final_final.csv',
                encoding='cp949', index=False)